// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfoyymywubpydrsoevqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmb3l5bXl3dWJweWRyc29ldnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDUxODcsImV4cCI6MjA3MTk4MTE4N30.nW91Z9KgwMFpBg83OZcF_4PRg-FDhqjHZk29Js8SopM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});